### ISSUE TITLE
build the project fail

### ISSUE THREAD

**Issue by yeqinggui** [maxgerhardt/pio-esp-mdf-example#1]
download the project and build，but the result is fail. 

[6/26] Building C object esp-idf/mdebug/CMakeFiles/__idf_mdebug.dir/mdebug_espnow.c.obj
ninja: build stopped: subcommand failed.
终端进程“C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja ”已终止，退出代码: 1。

**Comment by maxgerhardt** [comment]
This project is supposed to be build with PlatformIO, not the ESP-IDF build system like your log seems to indicate.
