### ISSUE TITLE
mbedtls/net.h: No such file or directory

### ISSUE THREAD

**Issue by hazra101** [maxgerhardt/pio-esp-mdf-example#3]
Hi, I have an assignment to complete my exam period. I used Arduino IDE programming with ESP32 to connect Firebase and telegram. however, in the middle of the way there are program errors such as 

c:\Users\LENOVO\Documents\Arduino\libraries\WiFiClientSecure\src/ssl_client.h:8:10: fatal error: mbedtls/net.h: No such file or directory

with the program as a whole:
#include <WiFi.h>
#include <FirebaseESP32.h>
#include <UniversalTelegramBot.h>
#include <WiFiClientSecure.h>
FirebaseData firebaseData;
FirebaseAuth auth;
Configure FirebaseConfig;
WiFiClientSecure Client;
UniversalTelegramBot bot(BOT_TOKEN, client);

// Timer for checking messages
unsigned long lastTime;
unsigned long checkInterval = 1000;

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);

  // Attempting to connect to WiFi
  Serial.print(“Connecting to WiFi...”);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(“.”);
  }
  Serial.println(“Connected to WiFi”);

  // Firebase setup
  config.host = FIREBASE_HOST;
  config.signer.tokens.legacy_token = FIREBASE_AUTH;

  Firebase.begin(&config, &auth);
  Firebase.reconnectWiFi(true);

  // Telegram client setup
  client.setInsecure();
}

void loop() {
  if (millis() - lastTime > checkInterval) {
    int numNewMessages = bot.getUpdates(bot.last_message_received + 1);

    while (numNewMessages) {
      Serial.println("Got response");
      handleNewMessages(numNewMessages);
      numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    }
    lastTime = millis();
  }
}

void handleNewMessages(int numNewMessages) {
  for (int i = 0; i < numNewMessages; i++) {
    String chat_id = String(bot.messages[i].chat_id);
    String text = bot.messages[i].text;

    // Print the received message
    Serial.println("Received message: " + text);

    // Update Firebase with the received message
    String path = "/loker1/rfid";
    if (Firebase.setString(firebaseData, path, text)) {
      Serial.println("Firebase update successful");
      bot.sendMessage(chat_id, "RFID updated successfully", "");
    } else {
      Serial.println("Firebase update failed: " + firebaseData.errorReason());
      bot.sendMessage(chat_id, "Failed to update RFID", "");
    }
  }
}

please, help me

**Comment by maxgerhardt** [comment]
What does a compile error regarding FirebaseESP32.h have to do with this ESP-MDF repo? I don't get it.

Based on the error message it seems very wrong that the WiFiClientSecure library is found in `c:\Users\LENOVO\Documents\Arduino\libraries\WiFiClientSecure`, it should be in the croe. Delete the folder entirely and recompile.
